PREFIX : <https://w3id.org/wifi-ontology#>

SELECT ?p ?nombre ?vel
WHERE {
  ?p a :PuntoWifi ;
     :estadoPunto "Activo" ;
     :nombrePunto ?nombre ;
     :tieneCobertura ?c .
  ?c :velocidadMedia ?vel .
}
ORDER BY DESC(?vel)
