PREFIX : <https://w3id.org/wifi-ontology#>

SELECT ?p ?nombre ?ssid ?vel
WHERE {
  ?p a :PuntoWifi ;
     :seUbicaEnZona :zona_CentroValencia ;
     :nombrePunto ?nombre ;
     :tieneSSID ?ssid ;
     :tieneCobertura ?c .
  ?c :velocidadMedia ?vel .
}
ORDER BY DESC(?vel)
