PREFIX : <https://w3id.org/wifi-ontology#>

SELECT ?z ?nombreZona
WHERE {
  ?z a :ZonaUrbana ;
     :nombreZona ?nombreZona .

  FILTER NOT EXISTS {
    ?p a :PuntoWifi ;
       :seUbicaEnZona ?z ;
       :estadoPunto "Activo" .
  }
}
ORDER BY ?nombreZona